# Generated by Django 5.2.3 on 2025-06-26 20:26

import django.core.validators
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('tree_picture', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, None], upload_to='images/specials/%Y/%m/%d/')),
                ('tree_picture2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, None], upload_to='images/specials/%Y/%m/%d/')),
                ('tree_picture3', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[400, None], upload_to='images/specials/%Y/%m/%d/')),
                ('special_place_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location_name', models.CharField(max_length=80)),
                ('location_description', models.TextField()),
                ('coordinates', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('time_now', models.DateTimeField(auto_now=True)),
                ('uploader', models.CharField(blank=True, max_length=50, null=True)),
                ('tree_specie_found', models.ManyToManyField(to='trees.tree')),
            ],
        ),
    ]
