# Generated by Django 5.2.3 on 2025-06-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('search_by', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
