# Generated by Django 5.2.3 on 2025-06-26 20:26

import django.core.validators
import django.db.models.deletion
import django_resized.forms
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tree_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('tree_picture', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, None], upload_to='images/uploads/%Y/%m/%d/')),
                ('tree_picture2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, None], upload_to='images/uploads/%Y/%m/%d/')),
                ('tree_picture3', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, None], upload_to='images/uploads/%Y/%m/%d/')),
                ('location_name', models.CharField(max_length=80)),
                ('location_description', models.TextField()),
                ('coordinates', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('time_now', models.DateTimeField(auto_now=True)),
                ('health_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.treestatus')),
            ],
            options={
                'ordering': ['location_name'],
            },
        ),
    ]
