# Generated by Django 5.2.3 on 2025-06-26 23:12

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='tree_picture',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[2048, None], upload_to='images/uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='tree_picture2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, None], upload_to='images/uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='tree_picture3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, None], upload_to='images/uploads/%Y/%m/'),
        ),
    ]
