# Generated by Django 5.2.3 on 2025-06-26 20:26

import django_resized.forms
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('location_name', models.CharField(max_length=100)),
                ('location_description', models.TextField()),
                ('tree_picture', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[800, None], upload_to='images/request/%Y/%m/%d')),
                ('tree_picture2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[600, None], upload_to='images/request/%Y/%m/%d/')),
                ('coordinates', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('validated', models.BooleanField(default=False)),
                ('requested', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['requested'],
            },
        ),
    ]
